name: Build and deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install node dependencies
        run: npm install -d ./www
      - name: build
        run: npm build -d ./www 
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: ./www/www/
  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with: 
          name: dist
          path: ${{ vars.WORK_DIR }}
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with: 
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_usr }}
          password: ${{ secrets.ftp_password }}