name: Build and deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build ⛏
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      # - name: Cache composer dependencies
      #   uses: actions/cache@v2
      #   with:
      #       path: www/vendor
      #       key: composer-${{ hashFiles('**/composer.lock') }}
      #       restore-keys: |
      #           composer-
      # - name: Setup PHP, with composer and extensions
      #   uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
      #   with:
      #     php-version: '8.2'
      #     extensions: mbstring, bcmath
      #     coverage: xdebug
      - name: Install node dependencies
        run: npm i -d ./www
      - name: Install ionic/cli dependencies
        run: npm i @ionic/cli -d ./www
      - name: Prepare angular Application
        run: |
          cd www
          ionic build --prod
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: ./www/www/
  deploy:
    name: Deploy 🚀
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with: 
          name: dist
          path: ${{ vars.WORK_DIR }}
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with: 
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_usr }}
          password: ${{ secrets.ftp_password }}